apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: asia-southeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: helloHttp
    run.googleapis.com/build-image-uri: asia-southeast1-docker.pkg.dev/lparmy/cloud-run-source-deploy/nylago
    run.googleapis.com/build-name: projects/594680195221/locations/asia-southeast1/builds/fe0e3561-6e2b-4160-945e-9cc247644b56
    run.googleapis.com/build-source-location: gs://run-sources-lparmy-asia-southeast1/services/nylago/1755360043.649000.zip#1755360044641071
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/urls: '["https://nylago-594680195221.asia-southeast1.run.app","https://nylago-xyoxbqdz6a-as.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-southeast1
    run.googleapis.com/satisfiesPzs: 'true'
  name: nylago
  namespace: '594680195221'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/base-images: '{"nylago-1":"asia-southeast1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: asia-southeast1-docker.pkg.dev/lparmy/cloud-run-source-deploy/nylago@sha256:956cb41d24c4782ed1054cb25d43d8962f5ac282e8d6fd0ad0d019c705a2a857
        name: nylago-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: 594680195221-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
